name: Deploy no Kubernetes
on:
    workflow_call:
      inputs:
        manifests:
          type: string
          required: true
          description: "Arquivos de manifesto para deploy"
        images:
          type: string
          required: true
          description: "Imagens que serão utilizadas no manifesto"
jobs:
    deploy-k8s:
        runs-on: ubuntu-latest
        needs: [CI]
        steps:
        - name: Setup doctl
          uses: digitalocean/action-doctl@v2
          with:
          token: ${{ secrets.DO_TOKEN }}

        - name: Obtendo o código
          uses: actions/checkout@v4.1.5

        - name: Configuração de contexto do Kubernetes
          uses: azure/k8s-set-context@v4
          with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}

        - name: Execução do Manifesto
          uses: Azure/k8s-deploy@v5
          with:
          manifests: |
              ${{ inputs.manifests }}
          images: |
              ${{ inputs.images }}
