name: CI-CD
on: 
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o código
        uses: actions/checkout@v4.1.5
      - name: Autenticação no Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build da Imagem Docker
        uses: docker/build-push-action@v6
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: | 
            limalucas99/aula-primeira-pipeline:v${{ github.run_number }}
            limalucas99/aula-primeira-pipeline:latest
  CD:
    needs: [CI]
    uses: limalucas99/primeira-pipeline-cicd/.github/workflows/deploy.yml@main
    with:
      manifests: ./k8s/deployment.yml
      images: limalucas99/aula-primeira-pipeline:v${{ github.run_number }}
    secrets: inherit